// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testhorizontallayoutcontainer.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the TestHorizontalLayoutContainer module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_TestContainer_NewItemBuilder(
		testhorizontallayoutcontainer.proxies.TestContainer _testContainer
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("TestHorizontalLayoutContainer.ACT_TestContainer_NewItem");
		builder = builder.withParam("TestContainer", _testContainer);
		return builder;
	}

	public static void aCT_TestContainer_NewItem(
		IContext context,
		testhorizontallayoutcontainer.proxies.TestContainer _testContainer
	)
	{
		aCT_TestContainer_NewItemBuilder(
				_testContainer
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_TestContainer_SaveEditBuilder(
		testhorizontallayoutcontainer.proxies.TestContainer _testContainer
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("TestHorizontalLayoutContainer.ACT_TestContainer_SaveEdit");
		builder = builder.withParam("TestContainer", _testContainer);
		return builder;
	}

	public static void aCT_TestContainer_SaveEdit(
		IContext context,
		testhorizontallayoutcontainer.proxies.TestContainer _testContainer
	)
	{
		aCT_TestContainer_SaveEditBuilder(
				_testContainer
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_TestContainer_SaveNewBuilder(
		testhorizontallayoutcontainer.proxies.TestContainer _testContainer
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("TestHorizontalLayoutContainer.ACT_TestContainer_SaveNew");
		builder = builder.withParam("TestContainer", _testContainer);
		return builder;
	}

	public static void aCT_TestContainer_SaveNew(
		IContext context,
		testhorizontallayoutcontainer.proxies.TestContainer _testContainer
	)
	{
		aCT_TestContainer_SaveNewBuilder(
				_testContainer
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder vAL_TestContainerBuilder(
		testhorizontallayoutcontainer.proxies.TestContainer _testContainer
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("TestHorizontalLayoutContainer.VAL_TestContainer");
		builder = builder.withParam("TestContainer", _testContainer);
		return builder;
	}

	public static boolean vAL_TestContainer(
		IContext context,
		testhorizontallayoutcontainer.proxies.TestContainer _testContainer
	)
	{
		Object result = vAL_TestContainerBuilder(
				_testContainer
			)
			.execute(context);
		return (boolean) result;
	}
}
