// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datawidgets.proxies;

public enum Filter_Operators
{
	contains("eb3129d1-bc8d-4309-94fe-beea07555263"),
	startsWith("0d60b4f6-5de2-4c4d-ae50-5e9731014761"),
	endsWith("fa9ecd23-753e-4a22-a9cd-040fd0c9732d"),
	between("b7c86830-1c1f-437d-bc36-ec44c973b5de"),
	greater("f02c85fb-2aec-4266-bed6-55dbccc9a219"),
	greaterEqual("c72ed089-6b70-4bae-be98-af6456c747d7"),
	equal("7ad1ccda-7356-4de8-ad73-2a3a5f211a9d"),
	notEqual("2b884f98-504e-47bb-ab31-24334d7b832f"),
	smaller("b3b0876e-a4ad-412e-90cd-9a00a1c03d7e"),
	smallerEqual("8191d04a-9a59-4333-8e1d-fa87c40ebdce"),
	empty("043fc410-1c57-45bd-a11f-cc023913e272"),
	notEmpty("20a566a6-ef6f-4d3b-aaf3-82f79f4db513");

	private final java.lang.String i18nCaptionKey;
	
	private Filter_Operators(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
