// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datawidgets.proxies;

public enum Filter_Operators
{
	contains("406c3d71-9bc3-41d1-8872-1e6650989612"),
	startsWith("24499150-41a9-48f3-939c-a7b29511230e"),
	endsWith("dc7d66a2-b787-42df-84a9-8c31bfa940f9"),
	between("f9ee300d-c7cc-4471-bf48-6e8dd647d674"),
	greater("b8511eb2-6373-421b-8dbb-ad73b81dcb90"),
	greaterEqual("11a1d830-85d4-412e-92e2-9f65c7f8674b"),
	equal("bec09b9c-396e-4e79-88f3-673d3aeab25f"),
	notEqual("21944fd6-bf42-43c8-b858-e670084354a4"),
	smaller("d56ea675-33d1-4309-823c-6e17da74647d"),
	smallerEqual("7aa12d1e-40db-4af2-ac2e-e57a2c02f306"),
	empty("0013c362-55ac-4736-8f63-f9bb8e99d0ae"),
	notEmpty("64a1340c-ddec-4676-aa57-0fb743927aec");

	private final java.lang.String i18nCaptionKey;
	
	private Filter_Operators(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
